AdobeDocs/cis-photoshop-api-docs

static/api_response_402_error_schema.json, static/swagger.json
=> updated swagger.json

src/pages/getting-started/index.md, src/pages/hello-world/index.md, src/pages/index.md
=> modified the pre release url

static/swagger.json
=> modified the ref path for smartObject

static/PITS/adjustments.schema.json, static/PITS/bounds.schema.json, static/PITS/fontColor.schema.json, static/PITS/swaggerspike.json, static/PITS/text.schema.json
=> adding the dependent files

static/PITS/post_smart_object.schema.json
=> modifying ref

static/PITS/post_smart_object.schema.json, static/swagger.json
=> adding smartObject API

static/PITS/post_action_json.schema.json, static/PITS/post_layer_brightness_contrast.schema.json, static/PITS/post_smart_object_v2.schema.json, static/PITS/preferences.schema.json
=> Automation: Updated static/PITS.

static/acr/outputs.schema.json
=> Automation: Updated static/acr.

src/pages/code-sample/index.md, static/acr/post_xmp.schema.json, static/swagger.json
Enable flip/rotate features through the `orientation` option as part of the `/xmp` API
=> Lr orientation

sample-code/azure-blob-text-edit/.gitignore, sample-code/azure-blob-text-edit/README.md, sample-code/azure-blob-text-edit/app.js
added example `azure-blob-text-edit`.  This is end-to-end, it shows how to generate a IMS JWT Token, generate SAS url for azure, and call the Photoshop Text API.
=> added azure-blob-text-edit

sample-code/s3-smart-object-replacement/.gitignore, sample-code/s3-smart-object-replacement/README.md, sample-code/s3-smart-object-replacement/app.js, sample-code/s3-smart-object-replacement/package-lock.json, sample-code/s3-smart-object-replacement/package.json, src/pages/code-sample/index.md
end-to-end example of how to do a smartObject replacement
=> added s3-smart-object-replacement example

src/pages/code-sample/index.md, static/PITS/get_status.schema.json, static/swagger.json
fix link to various get status API
=> fix broken status link

static/ic/post_cutout.schema.json
=> Automation: Updated static/ic.

static/PITS/get_manifest_status.schema.json, static/PITS/get_status.schema.json, static/acr/get_status.schema.json, static/ic/get_status.schema.json, static/swagger.json
Changes in this PR:
(1) Updated status/enum.
(2) Updated status code from 202 to 200 to match the actual response code.
(3) Minor things, such as removing ., upper case vs lower case, etc.
=> [DISE-6114] Updated get status API docs

src/pages/code-sample/index.md
fonts should be an array of objects not just and object
=> fonts should be an array of objects not just and object

src/pages/index.md
=> removed the section Beta to be at par with aws marketplace

src/pages/features/index.md
=> removed pre-release language

gatsby-config.js, src/pages/billing-metrics/index.md
=> adding the page billing metrics

sample-code/ic-customized-workflow-app/IC_customized_workflow_using_S3.sh, sample-code/ic-customized-workflow-app/IC_customized_workflow_using_cc_storage.sh, src/pages/code-sample/index.md, src/pages/features/index.md, static/swagger.json
=> Rebranding ImageCutout to Remove Background

static/swagger.json
=> fixed typo

src/pages/billing-metrics/index.md, src/pages/general-workflow/index.md
=> added details for countries included for international

static/PITS/file_input.schema.json, static/PITS/file_output.schema.json, static/acr/inputs.schema.json, static/acr/outputs.schema.json
=> added schema fix

src/pages/code-sample/index.md
=> removed PEGASUS from Multiple file input variable for actionJSON

static/PITS/post_action_json.schema.json
=> fix for actionJSON ACTION_JSON_OPTIONS_ADDITIONAL_IMAGES_X

sample-code/storage-app/googledrive/package.json, sample-code/storage-app/googledrive/presignedURLs.js, sample-code/storage-app/googledrive/service-account.json, src/pages/general-workflow/index.md
=> example for presigned urls for assets on google drive

src/pages/general-workflow/index.md, static/swagger.json
=> changes for storage, api reference change for job status

static/swagger.json
=> updated with comments from Rays

src/pages/getting-started/index.md
=> changed the sample app url

src/pages/api/index.md, static/swagger.json
=> fix for typo in Remove Backgroud API reference

src/pages/features/index.md, static/PITS/file_output_action_json_create.schema.json, static/PITS/post_action_json_create.schema.json, static/swagger.json
=> changes related to .atn to actionJson API and Ray's video emabedded

src/pages/getting-started/index.md
=> Modified Getting Started and Overview page for Summit Release

static/PITS/file_input.schema.json, static/PITS/file_output.schema.json, static/PITS/file_output_action_json_create.schema.json, static/PITS/file_output_pegasus.schema.json, static/PITS/post_action_json.schema.json, static/acr/inputs.schema.json, static/acr/outputs.schema.json, static/ic/post_cutout.schema.json
=> removed /files option for CC Files EOL

static/api_response_402_error_schema.json
=> updated the error message
